name: Snyk Security Scan

on:
  push:
  workflow_dispatch:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: nnpm install --legacy-peer-deps

    - name: Compile the app
      run: npm run build

    - name: Install Snyk
      run: npm install -g snyk

    - name: Run Snyk SCA
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk test

    - name: Run Snyk SAST
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk code test
